name: Validation Action
description: |
  Validates the input values against formats, patterns, ranges, character sets, and other user-defined rules.

inputs:
  value:
    required: true
    description: The value to validate.
  not-empty:
    required: false
    description: Validates whether the input value is not empty.
  digit:
    required: false
    description: Validates whether the input value contains only digits (0-9).
  alpha:
    required: false
    description: Validates whether the input value contains only English letters (a-zA-Z).
  alphanumeric:
    required: false
    description: Validates whether the input value contains only English letters and digits (a-zA-Z0-9).
  ascii:
    required: false
    description: Validates whether the input value contains only ASCII characters.
  printable-ascii:
    required: false
    description: Validates whether the input value contains only printable ASCII characters.
  int:
    required: false
    description: Validates whether the input value is an integer.
  float:
    required: false
    description: Validates whether the input value is a floating-point number.
  url:
    required: false
    description: Validates whether the input value is a valid URL.
  email:
    required: false
    description: Validates whether the input value is a valid email address.
  semver:
    required: false
    description: Validates whether the input value is a valid semantic version.
  uuid:
    required: false
    description: Validates whether the input value is a valid UUID.
  base64:
    required: false
    description: Validates whether the input value is valid Base64.
  json:
    required: false
    description: Validates whether the input value is valid JSON.
  exact-length:
    required: false
    description: Validates whether the input value's length is exactly equal to the specified number.
  min-length:
    required: false
    description: Validates whether the input value's length is greater than or equal to the specified minimum.
  max-length:
    required: false
    description: Validates whether the input value's length is less than or equal to the specified maximum.
  min:
    required: false
    description: Validates whether the input value is greater than or equal to the specified minimum.
  max:
    required: false
    description: Validates whether the input value is less than or equal to the specified maximum.
  enum:
    required: false
    description: Validates whether the input value matches any of the specified enumerations.
  timestamp:
    required: false
    description: Validates whether the input value matches a timestamp format [rfc3339, datetime, date, time].
  pattern:
    required: false
    description: Validates whether the input value matches the specified regular expression.


runs:
  using: composite

  steps:
    - name: Check Cosign is installed
      id: installed
      run: |
        echo "::group::Check Cosign is installed"
        set -x
        installed="false"
        if [ "$(which cosign)" ]; then
          installed="true"
        fi;
        echo "cosign=${installed}" >> "${GITHUB_OUTPUT}"
        echo "::endgroup::"
      shell: bash

    - name: Install Cosign
      uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0
      if: ${{ steps.installed.outputs.cosign == 'false' }}

    - name: Pull and verify image
      id: image
      env:
        IMAGE_REPOSITORY: tmknom/valid
        IMAGE_DIGEST: sha256:12845188766d5d61c4c306905200789c9326c75b5dc9d480c72b03e30d043e5e # v0.3.1
        IMAGE_SOURCE_DIGEST: 835ae13755d072358f4027dedeb5ec19046312f8
        IMAGE_SIGNER_DIGEST: c828b3f16d93cced26547858bf2f73c9790f3099
        IMAGE_SIGNER_WORKFLOW: https://github.com/tmknom/release-workflows/.github/workflows/go.yml
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        echo "::group::Pull and verify image"
        set -x
        image="ghcr.io/${IMAGE_REPOSITORY}@${IMAGE_DIGEST}"
        echo "repo-digest=${image}" >> "${GITHUB_OUTPUT}"
        docker pull "${image}"

        cosign verify \
          --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
          --certificate-identity "${IMAGE_SIGNER_WORKFLOW}@${IMAGE_SIGNER_DIGEST}" \
          --certificate-github-workflow-repository "${IMAGE_REPOSITORY}" \
          --certificate-github-workflow-sha "${IMAGE_SOURCE_DIGEST}" \
          "${image}" 2>/dev/null

        gh attestation verify "oci://${image}" \
          --deny-self-hosted-runners \
          --cert-oidc-issuer "https://token.actions.githubusercontent.com" \
          --cert-identity "${IMAGE_SIGNER_WORKFLOW}@${IMAGE_SIGNER_DIGEST}" \
          --repo "${IMAGE_REPOSITORY}"

        docker run --interactive --rm --user 1111:1111 --read-only \
          --security-opt no-new-privileges --cap-drop all --network none \
          "${image}" --version
        echo "::endgroup::"
      shell: bash

    - name: Run valid
      env:
        IMAGE_REPO_DIGEST: ${{ steps.image.outputs.repo-digest }}
        VALUE: ${{ inputs.value }}
        NOT_EMPTY: ${{ inputs.not-empty }}
        DIGIT: ${{ inputs.digit }}
        ALPHA: ${{ inputs.alpha }}
        ALPHANUMERIC: ${{ inputs.alphanumeric }}
        ASCII: ${{ inputs.ascii }}
        PRINTABLE_ASCII: ${{ inputs.printable-ascii }}
        INT: ${{ inputs.int }}
        FLOAT: ${{ inputs.float }}
        URL: ${{ inputs.url }}
        EMAIL: ${{ inputs.email }}
        SEMVER: ${{ inputs.semver }}
        UUID: ${{ inputs.uuid }}
        BASE64: ${{ inputs.base64 }}
        JSON: ${{ inputs.json }}
        EXACT_LENGTH: ${{ inputs.exact-length }}
        MIN_LENGTH: ${{ inputs.min-length }}
        MAX_LENGTH: ${{ inputs.max-length }}
        MIN: ${{ inputs.min }}
        MAX: ${{ inputs.max }}
        ENUM: ${{ inputs.enum }}
        TIMESTAMP: ${{ inputs.timestamp }}
        PATTERN: ${{ inputs.pattern }}
      run: |
        echo "::group::Run valid"
        set -x
        flags=(--value "${VALUE}")

        if [[ "${NOT_EMPTY}" != "" && "${NOT_EMPTY}" != "false" ]]; then
          flags+=(--not-empty)
        fi

        if [[ "${DIGIT}" != "" && "${DIGIT}" != "false" ]]; then
          flags+=(--digit)
        fi

        if [[ "${ALPHA}" != "" && "${ALPHA}" != "false" ]]; then
          flags+=(--alpha)
        fi

        if [[ "${ALPHANUMERIC}" != "" && "${ALPHANUMERIC}" != "false" ]]; then
          flags+=(--alphanumeric)
        fi

        if [[ "${ASCII}" != "" && "${ASCII}" != "false" ]]; then
          flags+=(--ascii)
        fi

        if [[ "${PRINTABLE_ASCII}" != "" && "${PRINTABLE_ASCII}" != "false" ]]; then
          flags+=(--printable-ascii)
        fi

        if [[ "${INT}" != "" && "${INT}" != "false" ]]; then
          flags+=(--int)
        fi

        if [[ "${FLOAT}" != "" && "${FLOAT}" != "false" ]]; then
          flags+=(--float)
        fi

        if [[ "${URL}" != "" && "${URL}" != "false" ]]; then
          flags+=(--url)
        fi

        if [[ "${EMAIL}" != "" && "${EMAIL}" != "false" ]]; then
          flags+=(--email)
        fi

        if [[ "${SEMVER}" != "" && "${SEMVER}" != "false" ]]; then
          flags+=(--semver)
        fi

        if [[ "${UUID}" != "" && "${UUID}" != "false" ]]; then
          flags+=(--uuid)
        fi

        if [[ "${BASE64}" != "" && "${BASE64}" != "false" ]]; then
          flags+=(--base64)
        fi

        if [[ "${JSON}" != "" && "${JSON}" != "false" ]]; then
          flags+=(--json)
        fi

        if [[ "${EXACT_LENGTH}" != "" ]]; then
          flags+=(--exact-length "${EXACT_LENGTH}")
        fi

        if [[ "${MIN_LENGTH}" != "" ]]; then
          flags+=(--min-length "${MIN_LENGTH}")
        fi

        if [[ "${MAX_LENGTH}" != "" ]]; then
          flags+=(--max-length "${MAX_LENGTH}")
        fi

        if [[ "${MIN}" != "" ]]; then
          flags+=(--min "${MIN}")
        fi

        if [[ "${MAX}" != "" ]]; then
          flags+=(--max "${MAX}")
        fi

        if [[ "${ENUM}" != "" ]]; then
          flags+=(--enum "${ENUM}")
        fi

        if [[ "${TIMESTAMP}" != "" ]]; then
          flags+=(--timestamp "${TIMESTAMP}")
        fi

        if [[ "${PATTERN}" != "" ]]; then
          flags+=(--pattern "${PATTERN}")
        fi

        docker run --interactive --rm --user 1111:1111 --read-only \
          --security-opt no-new-privileges --cap-drop all --network none \
          "${IMAGE_REPO_DIGEST}" "${flags[@]}"
        echo "::endgroup::"
      shell: bash

branding:
  icon: check-circle
  color: green
