name: Merge
on:
  pull_request:
    paths: [".github/workflows/*.yml", ".github/workflows/*.yaml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  call:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login == 'dependabot[bot]' }}
    uses: tmknom/merge-workflows/.github/workflows/github-actions.yml@v0
    with:
      pull-request: ${{ github.event.pull_request.number }}
    permissions:
      contents: write
      pull-requests: write
