name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test-not-empty:
    name: Test not-empty
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: foo
            not-empty: true
            expected: success
          - value: foo
            not-empty: false
            expected: success
          - value: ''
            not-empty: 'true'
            expected: failure
          - value: ''
            not-empty: 'false'
            expected: success
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          not-empty: ${{ matrix.not-empty }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-digit:
    name: Test digit
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: 123
            digit: true
            expected: success
          - value: 123abc
            digit: true
            expected: failure
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          digit: ${{ matrix.digit }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-alpha:
    name: Test alpha
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: abcXYZ
            alpha: true
            expected: success
          - value: abcXYZ123
            alpha: true
            expected: failure
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          alpha: ${{ matrix.alpha }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-alphanumeric:
    name: Test alphanumeric
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: abcXYZ123
            alphanumeric: true
            expected: success
          - value: abcXYZ123<>
            alphanumeric: true
            expected: failure
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          alphanumeric: ${{ matrix.alphanumeric }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"
