name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test-not-empty:
    name: Test not-empty
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: foo
            not-empty: true
            expected: success
          - value: foo
            not-empty: false
            expected: success
          - value: ""
            not-empty: "true"
            expected: failure
          - value: ""
            not-empty: "false"
            expected: success
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          not-empty: ${{ matrix.not-empty }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-digit:
    name: Test digit
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: 123
            digit: true
            expected: success
          - value: 123abc
            digit: true
            expected: failure
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          digit: ${{ matrix.digit }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-alpha:
    name: Test alpha
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: abcXYZ
            alpha: true
            expected: success
          - value: abcXYZ123
            alpha: true
            expected: failure
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          alpha: ${{ matrix.alpha }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-alphanumeric:
    name: Test alphanumeric
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: abcXYZ123
            alphanumeric: true
            expected: success
          - value: abcXYZ123<>
            alphanumeric: true
            expected: failure
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          alphanumeric: ${{ matrix.alphanumeric }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-ascii:
    name: Test ascii
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: abcXYZ123<>
            ascii: true
            expected: success
          - value: abcABC123<>あ
            ascii: true
            expected: failure
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          ascii: ${{ matrix.ascii }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-printable-ascii:
    name: Test printable-ascii
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: abcXYZ123<>
            printable-ascii: true
            expected: success
          - value: abcABC123<>あ
            printable-ascii: true
            expected: failure
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          printable-ascii: ${{ matrix.printable-ascii }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-int:
    name: Test int
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: 123
            int: true
            expected: success
          - value: 123.4
            int: true
            expected: failure
          - value: abc
            int: true
            expected: failure
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          int: ${{ matrix.int }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-float:
    name: Test float
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: 123
            float: true
            expected: success
          - value: 123.4
            float: true
            expected: success
          - value: abc
            float: true
            expected: failure
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          float: ${{ matrix.float }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-url:
    name: Test url
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: https://example.com
            url: true
            expected: success
          - value: https://localhost:8080/test.html
            url: true
            expected: success
          - value: example.com
            url: true
            expected: failure
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          url: ${{ matrix.url }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-exact-length:
    name: Test exact-length
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: abc
            exact-length: 3
            expected: success
          - value: ab
            exact-length: 3
            expected: failure
          - value: abcd
            exact-length: 3
            expected: failure
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          exact-length: ${{ matrix.exact-length }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-min-length:
    name: Test min-length
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: abc
            min-length: 3
            expected: success
          - value: ab
            min-length: 3
            expected: failure
          - value: abcd
            min-length: 3
            expected: success
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          min-length: ${{ matrix.min-length }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-max-length:
    name: Test max-length
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: abc
            max-length: 3
            expected: success
          - value: ab
            max-length: 3
            expected: success
          - value: abcd
            max-length: 3
            expected: failure
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          max-length: ${{ matrix.max-length }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-min:
    name: Test min
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: 5
            min: 5
            expected: success
          - value: 5
            min: 4
            expected: success
          - value: 5
            min: 6
            expected: failure
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          min: ${{ matrix.min }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-max:
    name: Test max
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: 5
            max: 5
            expected: success
          - value: 5
            max: 4
            expected: failure
          - value: 5
            max: 6
            expected: success
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          max: ${{ matrix.max }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-enum:
    name: Test enum
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: foo
            enum: foo
            expected: success
          - value: bar
            enum: foo,bar,baz
            expected: success
          - value: invalid
            enum: foo,bar,baz
            expected: failure
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          enum: ${{ matrix.enum }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-timestamp:
    name: Test timestamp
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: "2024-08-09T12:34:56+07:00"
            timestamp: rfc3339
            expected: success
          - value: "2024-08-09T12:34:56Z"
            timestamp: rfc3339
            expected: success
          - value: "2024-08-09T12:34:56"
            timestamp: rfc3339
            expected: failure
          - value: "2024-08-09 12:34:56"
            timestamp: datetime
            expected: success
          - value: "2024-08-09T12:34:56Z"
            timestamp: datetime
            expected: failure
          - value: "2024-08-09"
            timestamp: date
            expected: success
          - value: "12:34:56"
            timestamp: date
            expected: failure
          - value: "12:34:56"
            timestamp: time
            expected: success
          - value: "2024-08-09"
            timestamp: time
            expected: failure
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          timestamp: ${{ matrix.timestamp }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"

  test-pattern:
    name: Test pattern
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - value: "valid+=,.@-"
            pattern: '^[\w+=,.@-]+$'
            expected: success
          - value: "valid+=,.@-<>"
            pattern: '^[\w+=,.@-]+$'
            expected: failure
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true
        with:
          value: ${{ matrix.value }}
          pattern: ${{ matrix.pattern }}

      - name: Verify
        env:
          EXPECTED: ${{ matrix.expected }}
          ACTUAL: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${ACTUAL}" = "${EXPECTED}"
